export {default as Error404} from './Eror404.jsx'
export {default as EstructuraDatos} from './EstructuraDeDatosTemas.jsx'
export {default as GrafoArbol} from './GrafoArbol.jsx'
export {default as Home} from './Home.jsx'
export {default as Navbar} from './Navbar.jsx'
export {default as Nosotros} from './Nosotros.jsx'
export {default as Topix} from './Topic.jsx'
export {default as Head} from './Head.jsx'
