export {default as Error404} from './Eror404.jsx'
export {default as EstructuraDatos} from './EstructuraDeDatosTemas_.jsx'
export {default as GrafoArbol} from './GrafoArbol_.jsx'
export {default as Home} from './Home_.jsx'
export {default as Navbar} from './Navbar_.jsx'
export {default as Nosotros} from './Nosotros_.jsx'
export {default as Topix} from './Topic_.jsx'
export {default as Head} from './Head_.jsx'
